[package]
name = "scylla"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = "0.7"
tokio = { version = "1", features = ["full"] }
axum-server = { version = "0.6", features = ["tls-rustls"] }
ratatui = "0.29.0"
crossterm = "0.29.0"
rusqlite = { version = "0.37", features = ["bundled"] }